[package]
name = "sqelf"
version = "0.0.0"
authors = ["Datalust"]
edition = "2018"
license = "Apache-2.0"

[dependencies.futures]
version = "0.1"

[dependencies.tokio]
version = "0.1"

[dependencies.bytes]
version = "0.4"

[dependencies.libflate]
version = "0.1"

[dependencies.byteorder]
version = "1.0"

[dependencies.humantime]
version = "1"

[dependencies.string_cache]
version = "0.7"

[dependencies.inlinable_string]
version = "0.1"

[dependencies.serde]
version = "1"

[dependencies.serde_derive]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.failure]
version = "0.1"

[dependencies.chrono]
version = "0.4"
features = ["serde"]
